"""
report.py
---------
Generate a downloadable PDF-style HTML report from the analysis results.
"""

from __future__ import annotations
import io
import base64
from datetime import datetime

import matplotlib.pyplot as plt


def _fig_to_base64(fig: plt.Figure) -> str:
    """Convert a Matplotlib figure to a base64-encoded PNG string."""
    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=120, bbox_inches="tight",
                facecolor=fig.get_facecolor())
    buf.seek(0)
    return base64.b64encode(buf.read()).decode("utf-8")


def build_html_report(
    stats: dict,
    selected_user: str,
    figs: dict[str, plt.Figure],
) -> str:
    """
    Build a self-contained HTML report with embedded charts.

    Parameters
    ----------
    stats : dict  — output of fetch_stats()
    selected_user : str
    figs : dict   — keys are section names, values are Matplotlib figures

    Returns
    -------
    str — full HTML document as a string
    """
    now = datetime.now().strftime("%d %b %Y, %H:%M")

    def stat_card(label: str, value) -> str:
        return f"""
        <div class="stat-card">
          <div class="stat-value">{value:,}</div>
          <div class="stat-label">{label}</div>
        </div>"""

    stat_html = "".join([
        stat_card("Total Messages", stats["total_messages"]),
        stat_card("Total Words",    stats["total_words"]),
        stat_card("Media Shared",   stats["media_count"]),
        stat_card("Links Shared",   stats["link_count"]),
    ])

    charts_html = ""
    for title, fig in figs.items():
        if fig is None:
            continue
        img_b64 = _fig_to_base64(fig)
        charts_html += f"""
        <div class="chart-section">
          <h2>{title}</h2>
          <img src="data:image/png;base64,{img_b64}" alt="{title}" />
        </div>"""

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>WhatsApp Chat Analysis Report</title>
  <style>
    * {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      background: #0d1117;
      color: #e6edf3;
      padding: 40px 32px;
    }}
    header {{
      border-bottom: 2px solid #25D366;
      padding-bottom: 20px;
      margin-bottom: 32px;
    }}
    header h1 {{ font-size: 2rem; color: #25D366; }}
    header p  {{ color: #8b949e; margin-top: 6px; }}
    .stats-grid {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
      gap: 16px;
      margin-bottom: 40px;
    }}
    .stat-card {{
      background: #161b22;
      border: 1px solid #30363d;
      border-radius: 10px;
      padding: 20px;
      text-align: center;
    }}
    .stat-value {{ font-size: 2rem; font-weight: 700; color: #25D366; }}
    .stat-label {{ font-size: 0.85rem; color: #8b949e; margin-top: 4px; }}
    .chart-section {{
      margin-bottom: 40px;
      background: #161b22;
      border: 1px solid #30363d;
      border-radius: 10px;
      padding: 24px;
    }}
    .chart-section h2 {{
      font-size: 1.1rem;
      color: #e6edf3;
      margin-bottom: 16px;
      border-left: 3px solid #25D366;
      padding-left: 10px;
    }}
    .chart-section img {{ width: 100%; border-radius: 6px; }}
    footer {{
      text-align: center;
      color: #8b949e;
      font-size: 0.8rem;
      padding-top: 20px;
      border-top: 1px solid #21262d;
    }}
  </style>
</head>
<body>
  <header>
    <h1>📊 WhatsApp Chat Analysis</h1>
    <p>User: <strong>{selected_user}</strong> &nbsp;|&nbsp; Generated: {now}</p>
  </header>

  <section class="stats-grid">
    {stat_html}
  </section>

  {charts_html}

  <footer>
    Generated by WhatsApp Chat Analysis Tool &nbsp;•&nbsp; {now}
  </footer>
</body>
</html>"""
